// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 aPlane Authors

package main

import (
	"bufio"
	"context"
	"encoding/base64"
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/algorand/go-algorand-sdk/v2/client/v2/algod"
)

func main() {
	inPath := flag.String("in", "", "Path to TEAL source file")
	outPath := flag.String("out", "", "Path to Go output file")
	pkg := flag.String("pkg", "", "Go package name for output")
	varName := flag.String("var", "", "Go variable name for bytecode")
	url := flag.String("url", "https://mainnet-api.algonode.cloud", "Algod API URL")
	timeout := flag.Duration("timeout", 30*time.Second, "Algod request timeout")
	flag.Parse()

	if *inPath == "" || *outPath == "" || *pkg == "" || *varName == "" {
		fmt.Fprintln(os.Stderr, "usage: compile_teal -in <teal> -out <go> -pkg <pkg> -var <name> [-url <algod url>]")
		os.Exit(1)
	}

	teal, err := os.ReadFile(*inPath)
	if err != nil {
		fail("failed to read TEAL source: %v", err)
	}

	client, err := algod.MakeClient(*url, "")
	if err != nil {
		fail("failed to create algod client: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	result, err := client.TealCompile(teal).Do(ctx)
	if err != nil {
		fail("TEAL compile failed: %v", err)
	}

	bytecode, err := base64.StdEncoding.DecodeString(result.Result)
	if err != nil {
		fail("failed to decode compiled bytecode: %v", err)
	}

	if err := writeGoFile(*outPath, *pkg, *varName, bytecode); err != nil {
		fail("failed to write Go output: %v", err)
	}
}

func writeGoFile(path string, pkg string, varName string, bytecode []byte) (err error) {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintln(w, "// Code generated by internal/tools/compile_teal; DO NOT EDIT.")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintf(w, "package %s\n\n", pkg)
	_, _ = fmt.Fprintf(w, "var %s = []byte{\n", varName)

	for i, b := range bytecode {
		if i%12 == 0 {
			_, _ = fmt.Fprint(w, "\t")
		}
		_, _ = fmt.Fprintf(w, "0x%02x,", b)
		if i%12 == 11 {
			_, _ = fmt.Fprintln(w)
		}
	}
	if len(bytecode)%12 != 0 {
		_, _ = fmt.Fprintln(w)
	}
	_, _ = fmt.Fprintln(w, "}")

	return w.Flush()
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
